using System.Linq;
using System.Text;
using System.Linq;

namespace Clet;

/// <summary>
/// Strips terminal escape sequences from untrusted content before it reaches the terminal driver.
/// Removes ESC (\x1b), BEL (\x07), 8-bit CSI (\x9b), 8-bit OSC (\x9d), and C1 7-bit pairs
/// (\x1b@ through \x1b_) to prevent OSC clipboard hijack, window-title rewrite, link spoofing,
/// and other terminal-state abuses.
/// </summary>
/// <remarks>
/// See D-030 in specs/decisions.md for the rationale behind filtering at the clet layer
/// rather than relying on Terminal.Gui.
/// </remarks>
internal static class TerminalEscapeSanitizer
{
    /// <summary>
    /// Sanitizes user-supplied content by removing dangerous terminal control sequences.
    /// This method is safe to call on content that will be handed to Terminal.Gui views
    /// or rendered to ANSI output.
    /// </summary>
    /// <param name="input">The untrusted input string (may be null).</param>
    /// <returns>The sanitized string with all dangerous control codes removed, or null if input was null.</returns>
    public static string? Sanitize (string? input)
    {
        if (input is null)
        {
            return null;
        }

        if (input.Length == 0)
        {
            return string.Empty;
        }

        // Fast path: check if any dangerous bytes exist before allocating
        if (!ContainsDangerousBytes (input))
        {
            return input;
        }

        StringBuilder sb = new (input.Length);

        for (int i = 0; i < input.Length; i++)
        {
            char c = input [i];

            switch (c)
            {
                case '\x1b': // ESC
                    // Check for C1 7-bit pair: ESC followed by @ through _
                    if (i + 1 < input.Length && input [i + 1] >= '@' && input [i + 1] <= '_')
                    {
                        // Skip the ESC and the following character (C1 7-bit pair)
                        i++;
                    }

                    // Otherwise just strip the bare ESC
                    break;

                case '\x07': // BEL
                case '\x9b': // 8-bit CSI
                case '\x9d': // 8-bit OSC
                    // Strip these single-byte controls
                    break;

                default:
                    sb.Append (c);

                    break;
            }
        }

        return sb.ToString ();
    }

    /// <summary>
    /// Strips user-payload escape sequences from ANSI renderer output while preserving
    /// legitimate SGR sequences generated by the renderer itself.
    /// </summary>
    /// <remarks>
    /// The MarkdownHelpRenderer legitimately produces ANSI SGR sequences (color, bold, etc.)
    /// via Terminal.Gui's ANSI driver. However, user content embedded in the markdown could
    /// smuggle through dangerous OSC/C1 sequences. This method strips only the dangerous
    /// sequences (BEL, 8-bit CSI/OSC, bare non-SGR ESC sequences) while preserving
    /// standard SGR (\x1b[...m) and cursor/erase sequences the renderer needs.
    /// </remarks>
    /// <param name="renderedAnsi">The ANSI output from the renderer.</param>
    /// <returns>The output with dangerous escape sequences removed.</returns>
    public static string SanitizeRenderedOutput (string renderedAnsi)
    {
        if (string.IsNullOrEmpty (renderedAnsi))
        {
            return renderedAnsi ?? string.Empty;
        }

        // Fast path: if no dangerous bytes exist beyond normal ESC[, skip processing
        if (!ContainsDangerousOutputBytes (renderedAnsi))
        {
            return renderedAnsi;
        }

        StringBuilder sb = new (renderedAnsi.Length);

        for (int i = 0; i < renderedAnsi.Length; i++)
        {
            char c = renderedAnsi [i];

            switch (c)
            {
                case '\x1b':
                    if (i + 1 < renderedAnsi.Length)
                    {
                        char next = renderedAnsi [i + 1];

                        if (next == '[')
                        {
                            // CSI sequence — this is legitimate renderer output (SGR, cursor, erase)
                            // Pass through the entire sequence up to the terminating byte (0x40-0x7E)
                            sb.Append ('\x1b');
                            sb.Append ('[');
                            i += 2;

                            while (i < renderedAnsi.Length)
                            {
                                char seqChar = renderedAnsi [i];
                                sb.Append (seqChar);

                                // CSI terminates at bytes 0x40–0x7E
                                if (seqChar >= '@' && seqChar <= '~')
                                {
                                    break;
                                }

                                i++;
                            }
                        }
                        else if (next >= '@' && next <= '_')
                        {
                            // C1 7-bit pair (ESC @ through ESC _, excluding ESC [ which was handled above).
                            // Includes dangerous sequences like OSC (ESC ]), DCS (ESC P), etc.
                            // Strip the pair.
                            i++;
                        }
                        else
                        {
                            // Other ESC sequences — strip the ESC
                        }
                    }

                    // Trailing ESC at end of string — strip it
                    break;

                case '\x07': // BEL (used as OSC terminator)
                case '\x9b': // 8-bit CSI
                case '\x9d': // 8-bit OSC
                    // Strip these
                    break;

                default:
                    sb.Append (c);

                    break;
            }
        }

        return sb.ToString ();
    }

    private static bool ContainsDangerousBytes (string s)
    {
        return s.Any (c => c is '\x1b' or '\x07' or '\x9b' or '\x9d');
    }

    private static bool ContainsDangerousOutputBytes (string s)
    {
        if (s.Any (c => c is '\x07' or '\x9b' or '\x9d'))
        {
            return true;
        }

        // Also check for dangerous ESC sequences (not just ESC[)
        for (int i = 0; i < s.Length; i++)
        {
            if (s [i] == '\x1b' && i + 1 < s.Length)
            {
                char next = s [i + 1];

                // ESC ] is OSC — dangerous. Other C1 pairs (ESC @ through ESC _) excluding
                // ESC [ (which is CSI, handled separately in SanitizeRenderedOutput) are also dangerous.
                if (next >= '@' && next <= '_' && next != '[')
                {
                    return true;
                }
            }
        }

        return false;
    }
}
